### ISSUE TITLE
 Older tests not conforming to macro usage 

### ISSUE THREAD

**Issue by josemonsalve2** [SOLLVE/sollve_vv#10]
All of the following tests do not conform to macro usage and should be updated:

- [x] linked_list.c
- [x] mmm_target.c
- [x] mmm_target_parallel_for_simd.c
- [x] test_target_is_device_ptr.c
- [x] test_target_map_global_arrays.c
- [x] test_target_map_local_array.c
- [x] test_target_map_pointer.c
- [x] test_target_map_pointer_default.c 
- [x] test_target_map_scalar_default.c
- [x] test_target_map_struct_default.c
- [x] test_target_private.c 
- [x] test_target_data_map.c 
- [x] test_target_data_map_array_sections.c (ready for review)
- [x] test_target_data_map_classes.cpp
- [x] test_target_data_map_devices.c
- [x] test_target_data_use_device_ptr.c
- [x] test_target_enter_data_classes.cpp (no longer exist, new versions have macros) 
- [x] test_target_enter_data_classes.cpp (no longer exist, new versions have macros)
- [x] test_target_enter_data_malloced_array.c 
- [x] test_target_enter_exit_data_classes.cpp
- [x] test_target_enter_exit_data_depend.c (ready for review)
- [x] test_target_enter_exit_data_devices.c (ready for review)
- [x] test_target_enter_exit_data_if.c (ready for review)
- [x] test_target_enter_exit_data_map_global_array.c
- [x] test_target_enter_exit_data_map_malloced_array.c
- [x] test_target_enter_exit_data_struct.c
- [x] test_target_teams_distribute_collapse.c (ready for review)
- [x] test_target_update_from.c 
- [x] test_target_update_if.c 
- [x] test_target_update_to.c

**Comment by josemonsalve2** [comment]
@jhdavis8 let's try to get this one out of the way in the next week. I want to do this before tackling issue #36 
We can divide it up. Let's discuss it on Slack.

**Comment by josemonsalve2** [comment]
Done with `application_kernels/linked_list.c`

**Comment by josemonsalve2** [comment]
Done with `application_kernels/mmm_target.c`

**Comment by josemonsalve2** [comment]
Done with `application_kernels/mmm_target_parallel_for_simd.c`

**Comment by josemonsalve2** [comment]
Done with `target_data/test_target_data_map_devices.c` Also fixed `target/test_target_device.c` that was missing the descirption

**Comment by josemonsalve2** [comment]
Done with `test_target_is_device_ptr.c`

**Comment by tmh97** [comment]
Done with test_target_map_global_arrays.c

**Comment by tmh97** [comment]
Done with test_target_map_local_array.c

**Comment by jhdavis8** [comment]
I have changed the issue description so the list is now a checklist, that way we can just check off the entries that are done instead of leaving a comment for every test. I think the checks are visible to all.

**Comment by josemonsalve2** [comment]
For the test `test_target_private.c` Notice that we are setting the threads to 4, but this could be a different value. Whenever we fix this test, we need to fix this error.

**Comment by josemonsalve2** [comment]
This test also has a bug. When data is copied from the target regions, it is overwritten to the host. Therefore, there is a data race in the array on the host.

**Comment by josemonsalve2** [comment]
This is also the case for the Fortran version of this test
