### ISSUE TITLE
out of bounds access in tests/4.5/target_teams_distribute/test_target_teams_distribute_firstprivate.F90

### ISSUE THREAD

**Issue by shivaramaarao** [SOLLVE/sollve_vv#109]
at line 105:
d(x) = a(x) + b(x) + c(x) + privatized_array(MOD(x, 10)) + privatized

since x can be 10, 20 ... MOD(x, 10) can evaluate to zero, hence we'll access privatized_array(0)

but privatized_array's section is 1:10, 0 is an out of bounds index

this will lead to incorrect value reading of privatized_array and hence undefined results.

**Comment by spophale** [comment]
Thanks for reporting this @shivaramaarao.

**Comment by spophale** [comment]
See #110

**Comment by spophale** [comment]
Addressed in #130
