### ISSUE TITLE
Missing top-of-file comments for some tests

### ISSUE THREAD

**Issue by jhdavis8** [SOLLVE/sollve_vv#118]
**Describe the bug**
I've noticed that a few older tests are missing header comments. This may not be high-priority but I wanted to document it here so we remember to fix it.

**Test that it applies to**
There may be more but I have found the following to be missing the top of file comment. I will add more when I get the chance.

- [x] https://github.com/SOLLVE/sollve_vv/blob/master/tests/4.5/target/test_target_defaultmap.c
- [x] https://github.com/SOLLVE/sollve_vv/blob/master/tests/4.5/target/test_target_depends.c
- [x] https://github.com/SOLLVE/sollve_vv/blob/master/tests/4.5/target_update/test_target_update_depend.c
- [x] https://github.com/SOLLVE/sollve_vv/blob/master/tests/4.5/target_enter_exit_data/test_target_enter_exit_data_classes.cpp
- [x] https://github.com/SOLLVE/sollve_vv/blob/master/tests/4.5/target_enter_exit_data/test_target_enter_exit_data_map_malloced_array.c
- [x] https://github.com/SOLLVE/sollve_vv/blob/master/tests/4.5/target_enter_data/test_target_enter_data_depend.c
- [x] https://github.com/SOLLVE/sollve_vv/blob/master/tests/4.5/target_enter_data/test_target_enter_data_devices.c
- [x] https://github.com/SOLLVE/sollve_vv/blob/master/tests/4.5/target_enter_data/test_target_enter_data_global_array.c
- [x] https://github.com/SOLLVE/sollve_vv/blob/master/tests/4.5/target_enter_data/test_target_enter_data_struct.c

**Comment by tmh97** [comment]
Note: test_target_defaultmap.c does not compile on gcc

**Comment by tmh97** [comment]
Addressed the original two tests in a recent pull request. Should we leave this issue up in case similar tests surface?

**Comment by tmh97** [comment]
Just added what looks to be the rest of 'em
