### ISSUE TITLE
test_target_is_device_ptr.c fails on the host

### ISSUE THREAD

**Issue by simoatze** [SOLLVE/sollve_vv#122]
Consider the test case [test_target_is_device_ptr.c](https://github.com/SOLLVE/sollve_vv/blob/ce1242bc70bd6b5ad0d85c9469d8582fcecf6ae0/tests/4.5/target/test_target_is_device_ptr.c).

Is it supposed to execute correctly on the host?
I think is not, let me explain why to see what you guys think.

At line [30](https://github.com/SOLLVE/sollve_vv/blob/ce1242bc70bd6b5ad0d85c9469d8582fcecf6ae0/tests/4.5/target/test_target_is_device_ptr.c#L30) we have:

`array_device = (int *) omp_target_alloc(N*sizeof(int), omp_get_default_device());`

`omp_get_default_device()` will return an available target device. According to the definition of a target device in the spec, it does not include the host device, so whatever value this function returns will not represent the host. Therefore when this test runs on the host it will fail because `omp_target_alloc` it either allocates data on an available GPU (but the program is running on the host) or, if there are not available devices, the `omp_target_alloc` will likely return NULL and the test fails as well.

What do you think?

Thanks!
Simone

**Comment by spophale** [comment]
Yes, I see what you mean. There needs to be a check if the code is running on host or device. Thanks @simoatze !

**Comment by simoatze** [comment]
@spophale Thanks! There are a few more tests with the same issue.
Here a list of those I have found so far:

[test_target_data_map_to.c 
](https://github.com/SOLLVE/sollve_vv/blob/ce1242bc70bd6b5ad0d85c9469d8582fcecf6ae0/tests/4.5/target_data/test_target_data_map_from.c)
[test_target_data_map_from.c
](https://github.com/SOLLVE/sollve_vv/blob/ce1242bc70bd6b5ad0d85c9469d8582fcecf6ae0/tests/4.5/target_data/test_target_data_map_to.c)
[test_target_data_map_alloc.c 
](https://github.com/SOLLVE/sollve_vv/blob/ce1242bc70bd6b5ad0d85c9469d8582fcecf6ae0/tests/4.5/target_data/test_target_data_map_alloc.c)

**Comment by tmh97** [comment]
Looking into this!
- [ ] test_target_is_device_ptr.c
- [ ] test_target_data_map_to.c
- [ ] test_target_data_map_from.c
- [ ] test_target_data_map_alloc.c

**Comment by tmh97** [comment]
@simoatze Added a fix for this in PR's #133 and #126 where we check if `omp_target_alloc` returns NULL.  Thanks again!

**Comment by tmh97** [comment]
Closing this issue that was addressed in recent PR's.
