### ISSUE TITLE
Wrong variable mapped in test_target_teams_distribute_thread_limit.c?

### ISSUE THREAD

**Issue by estewart08** [SOLLVE/sollve_vv#123]
```
#define N 1024

int main() {
  OMPVV_TEST_OFFLOADING;
  int default_threads;
  int num_threads;
  int errors = 0;

#pragma omp target teams distribute map(from: default_threads)
  for (int x = 0; x < N; ++x) {
    if (omp_get_team_num() == 0) {
      default_threads = omp_get_thread_limit();
    }
  }

  OMPVV_WARNING_IF(default_threads == 1, "Test operated with one thread. Cannot test thread_limit clause.");
  OMPVV_TEST_AND_SET(errors, default_threads <= 0);

  if (default_threads > 0) {
#pragma omp target teams distribute thread_limit(default_threads / 2) map(from: default_threads)
    for (int x = 0; x < N; ++x) {
      if (omp_get_team_num() == 0) {
        num_threads = omp_get_thread_limit();
      }
    }

    OMPVV_TEST_AND_SET(errors, num_threads > default_threads / 2);
    OMPVV_WARNING_IF(num_threads < default_threads / 2, "Test was provided fewer threads than the thread_limit clause indicated. Still spec-conformant.");

  }

  OMPVV_REPORT_AND_RETURN(errors);
}
```
**Describe the bug**
In the second target pragma, I believe the from clause should map num_threads instead of default_threads as default threads is not used inside of the target. An added printf statement shows num_threads is not initialized.

**Test that it applies to**
test_target_teams_distribute_thread_limit.c

**To Reproduce**
 ***Assumes AOMP 11.0-1 is installed at /usr/lib/aomp and gfx906***
1. make VERBOSE=1 VERBOSE_TESTS=1 LOG=1 LOG_ALL=1 CC='/usr/lib/aomp/bin/clang -fopenmp -fopenmp-targets=amdgcn-amd-amdhsa -Xopenmp-target=amdgcn-amd-amdhsa -march=gfx906' all SOURCES=tests/4.5/target_teams_distribute/test_target_teams_distribute_thread_limit.c

**Expected behavior**
Expected num_threads be less than or equal to thread_limit. Shows 1 error and failed test.

**Compiler**
AOMP 11.0-1

**Accelerator hardware**
gfx906 - Radeon 7

**Comment by jhdavis8** [comment]
Yes, that looks like a bug. I'll make a PR to fix it today.

**Comment by jhdavis8** [comment]
See PR #125

**Comment by jhdavis8** [comment]
Thanks for the bug report!
