### ISSUE TITLE
test_target_map_struct_default.c fails if run with no device present

### ISSUE THREAD

**Issue by tob2** [SOLLVE/sollve_vv#127]
See also #12 

The problem is that the two target sections use:
```
#pragma omp target
    if (!omp_is_initial_device()) {
```
Hence, the variables do not get set and one operates on uninitialized memory.

This test case **does work** if one **removes this condition** (or sets it unconditionally to true).

**Comment by spophale** [comment]
Thanks @tob2 ! Somewhere in the development process we moved out focus completely to device offload. We will correct it for host execution.

**Comment by tmh97** [comment]
A potential solution: Replace the `if (!omp_is_inital_device)` within the target region with `if(isOffloading)`.
