### ISSUE TITLE
test_target_teams_distribute_default_firstprivate.F90 fails when run

### ISSUE THREAD

**Issue by k-yeung** [SOLLVE/sollve_vv#129]
tests/4.5/target_teams_distribute/test_target_teams_distribute_default_firstprivate.F90 fails both tests when compiled with GFortran (current git trunk) and run with an AMD GCN accelerator target.

```
[OMPVV_INFOMSG test_target_teams_distribute_default_firstprivate.F90:21] Test is running on device
[OMPVV_ERROR test_target_teams_distribute_default_firstprivate.F90:24]  Condition test_firstprivate_private() .ne. 0 failed
[OMPVV_ERROR test_target_teams_distribute_default_firstprivate.F90:25]  Condition test_firstprivate_first() .ne. 0 failed
[OMPVV_INFOMSG ompvv.F90:244] The value of errors is 2
[OMPVV_RESULT test_target_teams_distribute_default_firstprivate.F90] Test failed on the device.
```

If a write statement is added to print the value of d(x) being compared, they will all be zeroes.

The problem is that the 'default(firstprivate)' clause is being applied to all the variables (including d), so the result of the computation does not make it out of the enclosing construct.

From the OpenMP 4.5 specification:

2.15.1.1: Variables with implicitly determined data-sharing attributes are those that are referenced in a given construct, do not have predetermined data-sharing attributes, and are not listed in a data-sharing attribute clause on the construct.

2.15.3.1: The default clause explicitly determines the data-sharing attributes of variables that are referenced in a parallel, teams, or task generating construct and would otherwise be implicitly determined...

I believe this behaviour is correct according to the spec, as listing the variables in the 'map' clause does not count as being 'listed in a data-sharing attribute clause'.

**Comment by spophale** [comment]
Thanks @k-yeung for reporting it. Yes, I see what you mean by differentiating between data movement vs. data sharing attribute.

**Comment by jhdavis8** [comment]
See PR #131

**Comment by jhdavis8** [comment]
PR #131 has been merged.
