### ISSUE TITLE
Verfication issue in test_target_teams_distribute _parallel_for_firstprivate.c

### ISSUE THREAD

**Issue by timcramer** [SOLLVE/sollve_vv#13]
The target_teams_distribute_parallel_for_firstprivate.c test verification works on the assumption that the first private variable 'privatized' will be reset to the value 10 for each iteration. We think this assumption is only true when exactly one thread executes one interation of the outer loop. This might be the case a GPU. However, this means that the test fails on devices with fewer threads, so we think this might not correct and portable OpenMP code. We believe that the verification only works if we reset the value of 'privatized' to 10 between the two loops, which is not the case if we (for instance) only have one team with 8 threads.

‌

Do you agree or did we made a wrong assumption?

**Comment by timcramer** [comment]
Old comments from bitbucket:


Jose Monsalve Diaz
Ah! I see what you mean! This is an interesting point. Let me explore further. I need to double check with the specs! Will update later today.


Jose Monsalve Diaz
We have studied this and you are right.

We will separate the test for the “first”ization and the privatization part.

We also will include a check to make sure there are multiple number of teams and number of threads

We could also attempt to use scheduling to encourage a thread to take over multiple iterations.


Tim Cramer
Ok, thanks for the confirmation. Separation of the privatization part sounds good. However, I dont see how a loop schedule can fix the test since even for that you need to make assumptions on the amount of threads in order to guarantee a specific value for the firstprivate variable (at least as long you dont use a coditional for the increment of the variable).

**Comment by josemonsalve2** [comment]
@timcramer I have fixed the test and created a new one thanks to this conversation. I sent you an invitation to collaborate so I can add you as pull request reviewer. Thanks for your help!

**Comment by josemonsalve2** [comment]
Tim, 

I was thinking about your problem with the number of threads. I think this is a configuration parameter we need to implement for the whole suite. What I was thinking is we push this test as it is, and then we create a new issue were we try to add new flags for the makefile `NUM_DEVICE_THREADS`, `NUM_DEVICE_TEAMS`, `NUM_HOST_THREADS`

There will be some corner cases we will need to cover, but I feel this is a larger change than this issue covers

**Comment by timcramer** [comment]
Sounds good.

**Comment by josemonsalve2** [comment]
This issue was solved by PR #21 and #19, The remaining feature will be discussed in issue #22
