### ISSUE TITLE
test_target_teams_distribute_parallel_for_devices.c: wrong check, mult-dev handling

### ISSUE THREAD

**Issue by tob2** [SOLLVE/sollve_vv#140]
As found out by a colleague, there are two issues:

- If there is more than one device (e.g. host + offloading device), all but the last set array element of "isHost" is uninitialized. The problem that isHost[0] is set for the first loop iteration – and map(from:) to the host. Then isHost[1] is set – but due to map(from:) it starts with a full but uninitialized array, hence, after this loop iteration, isHost[0] is undefined and isHost[1] is set etc. (It does work by chance, if the variable is zero initialized such that only the last iteration survives.) — Solution: use 'tofrom:'
- Likewise the error check at the end: `OMPVV_TEST_AND_SET(errors, isHost[dev])` this will fail for the host; it might work if (see above) isHost is zero initialized on the device as then all but the last device is ignored in this check.

**Comment by jhdavis8** [comment]
In progress, see PR #141 by @tob2

**Comment by tob2** [comment]
Close  – as PR #141 fixes this and was merged on May 21, 2020.
