### ISSUE TITLE
Consider using cmake build.

### ISSUE THREAD

**Issue by ChinouneMehdi** [SOLLVE/sollve_vv#147]
**Is your feature request related to a problem? Please describe.**
There are some bugs that can be easily resolved by using CMake like #34 and #5

**Describe the solution you'd like**
CMake has many builtin functionalities that facilitate features checking, cross-platform programming, finding packages, testing, packaging ... etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by XzzX** [comment]
Is there interest in having a cmake-based build system? The current build system is hard to adapt, in particular for self-built compilers. I am working on a very simple one to compile the suite for our computers.
