### ISSUE TITLE
OMPVVLIB in the C tests build step fails with GCC 9.2.0 

### ISSUE THREAD

**Issue by mcytowski** [SOLLVE/sollve_vv#148]
**Describe the bug**
We are building and running the benchmark on Linux system with GCC 9.2.0 and V100. Compilation of most of the C tests is successful, however during runtime all of the C tests fail with the following error:
`libgomp: Cannot map target functions or variables (expected X-1, have X)`

**Test that it applies to**
All C tests.

**To Reproduce**
Clone the current repository, compile and run with GCC 9.2.0.

**Expected behavior**
Removing $OMPVVLIB from the build rules for C files in Makefile seems to be solving this issue:
`-       -$(QUIET)$(call loadModules,$(C_COMPILER_MODULE)) $(CCOMPILE) $(VERBOSE_MODE) $(DTHREADS) $(DTEAMS) $(HTHREADS) $< -o $(BINDIR)/$(notdir $@) $(OMPVVLIB) $(if $(LOG),$(RECORD)$(notdir $(@:.o=.log))\`
`+       -$(QUIET)$(call loadModules,$(C_COMPILER_MODULE)) $(CCOMPILE) $(VERBOSE_MODE) $(DTHREADS) $(DTEAMS) $(HTHREADS) $< -o $(BINDIR)/$(notdir $@)  $(if $(LOG),$(RECORD)$(notdir $(@:.o=.log))\`

**Compiler**
GCC 9.2.0

**Accelerator hardware**
V100

**Comment by spophale** [comment]
Are you using our Makefile ?

I did a quick test on Summit (also V100) with gcc 9.1.0, I don't see the same behavior.
Make command : 
make CC=gcc SOURCES=a.c all

Some tests pass, some fail but none report the runtime error you see. There is a possibility that this could be specific to 9.2.0.

**Comment by josemonsalve2** [comment]
Swaroop, @tmh97 and I also noticed the same issue with our UD systems. It happened after we started linking the static library to all the tests. This is certainly a bug of some sort in the compiler. But in the meantime we should provide a way to disable the static lib. 

@mcytowski I was thinking this could be an issue with the newlib version that we are using, but I am not sure. It only seems to happen with C

**Comment by spophale** [comment]
What is the version of your gcc @josemonsalve2 @tmh97 ?
I will verify if my repo is updated.

**Comment by josemonsalve2** [comment]
7.1 7.2 7.3 8.1 8.2 9.1 9.2 
I remember trying with 8.1 and 9.1. I'll run it with the other ones

**Comment by jhdavis8** [comment]
For now I could add a flag to disable linking the static lib. I could also set up the flag to disable the static lib test from running.

**Comment by josemonsalve2** [comment]
Same result for all the GCC versions

**Comment by spophale** [comment]
I wonder why I don't see the same on Summit. 
@jhdavis8 we may have to go back to the original thought of setting a flag for that specific test. I fear it may not be obvious to new users if we go the other way.

**Comment by mcytowski** [comment]
Hi all, thanks for looking at it. To answer previous questions. Yes, I was using makefile (make CC=gcc CXX=g++ all). I confirm that it only happens for C, I was able to compile and run most of Fortran and C++ tests for instance. I was able to test it with GCC 9.2.0 but if that is of interest I can have a try with GCC 10.1.0 as well.

**Comment by josemonsalve2** [comment]
I've tried 10.1 and it works for me

**Comment by mcytowski** [comment]
yes, same here. Works for 10.1.

**Comment by jhdavis8** [comment]
I will try to change the Makefile to only link the static library for the test that requires it

**Comment by jhdavis8** [comment]
See PR #153 for my fix.

**Comment by jhdavis8** [comment]
PR #153 is merged.
