### ISSUE TITLE
g++ compiler error when using `this` in update clause

### ISSUE THREAD

**Issue by dmcdougall** [SOLLVE/sollve_vv#17]
[Right here](https://github.com/SOLLVE/sollve_vv/blob/fc544d0226c7d8cc5c2634e43df0f3488a2e541b/tests/4.5/target_enter_exit_data/test_target_enter_exit_data_classes.cpp#L35) is where the error occurs.  I thought this was a reasonable thing to do until one of the Mentor Graphics folks pointed out to me that [you explicitly avoid using `this->` in a different test](https://github.com/SOLLVE/sollve_vv/blob/fc544d0226c7d8cc5c2634e43df0f3488a2e541b/tests/4.5/target/test_target_map_classes_default.cpp#L42-L46).

We should probably use the same workaround here.

**Comment by josemonsalve2** [comment]
Yes, this was a discussion we had a while ago.  There is a PR right now on on of the C++ tests that is trying to fix that, so I will add this code to it as well. Would it be ok if I add you for code review? I think this is really complicated. XLC actually supports this, but the wording in 4.5 is clear that you are not supposed to have expressions in there (IIIRC that is the issue). 

Anyhow. I will leave this open until we solve it.

**Comment by dmcdougall** [comment]
Happy to review code for you.

> but the wording in 4.5 is clear that you are not supposed to have expressions in there

Can you point me to the part of the spec that spells that out?

**Comment by josemonsalve2** [comment]
The description of the map clause says that the map clause receives a list item:

Section 2.15.5.1, page 216, line 17
```
The syntax of the map clause is as follows:
map([ [map-type-modifier[,]] map-type : ] list)
```

And the definition of list item is 

Section 2.1, page 27, line 20
```
A list item is a variable or array section. An extended list item is a list item or a function name.
```

In 5.0 this was fixed. The new syntax of the map clause says locator-list:
section 2.19.7.1, page 315, line 18-19
```
The syntax of the map clause is as follows:
19 map([ [map-type-modifier[,] [map-type-modifier[,] ...] map-type : ] locator-list)
```

And they extended the description to include what a locator list is:

In Section 2.1, page 39, line 7-10
```
A locator-list consists of a comma-separated collection of one or more locator list items.
A list item is a variable or an array section. An extended list item is a list item or a function name. A locator list item is any lvalue expression, including variables, or an array section.
```

**Comment by josemonsalve2** [comment]
@jhdavis8 you probably want to be aware of this as well

**Comment by dmcdougall** [comment]
Thanks for digging that up.  So it's technically correct for an OpenMP 4.5 compiler to reject mapping `this->var`.

**Comment by josemonsalve2** [comment]
Yes, but it is a pain! This gets complicated with attributes of classes that you want to map into the device. The work around is ugly.

**Comment by josemonsalve2** [comment]
I'm trying to tackle this issue, but for some reason the following code is not working. See commit 
2d176bd for the whole code.

The content of h_array is initialize to `i`, modify is called twice, therefore resulting in `3*i`. What's weird is that the content of `sum` and the array obtained through `getDeviceAttribute()` is correct.  But the `target exit data map(from:helpher_harray[0:size])` is not copying back any value. This happens in all of the compilers. 

```C++
    Simple(int s, int *err) : size(s) { 
      sum = 0;
      h_array = new int[size];

      // Initialize the array in the host
      for (int i = 0; i < size; i ++) 
        h_array[i] = i;

      // To obtain the error counter variable that is external
      errors = err;
      int * helper_harray = this->h_array;
      Simple * mySelf = this;
#pragma omp target enter data map(to: mySelf[0:1])
#pragma omp target enter data map(to: helper_harray[0:size])
    }   

    ~Simple() { 
      // Modify again to see if changes are copied over
      int *helper_harray = this->h_array;
      Simple * mySelf = this;
#pragma omp target exit data map(from: helper_harray[0:size])

      // checking results that are coming back from the target exit data
      for (int i = 0; i < N; ++i) {
        printf("%d\n", h_array[i]);
        OMPVV_TEST_AND_SET_VERBOSE(*errors, h_array[i] != 3*i);
      }   

#pragma omp target exit data map(from: mySelf[0:1])
      OMPVV_TEST_AND_SET_VERBOSE(*errors, sum != 3*N*(N-1)/2);
      delete[] h_array; 
    }   

    void modify() {
      int * helper_harray = this->h_array;
      int &helper_sum = this->sum;
      int &helper_size = this->size;
#pragma omp target defaultmap(tofrom:scalar)
      {   
        helper_sum = 0;
        for (int i = 0; i < helper_size; ++i) {
          helper_harray[i] += i;
          helper_sum += helper_harray[i];
        }
      }   
    }   
```

The output of executing it is:
```
test_target_enter_exit_data_classes_simple.cpp.o:
[OMPVV_ERROR: test_target_enter_exit_data_classes_simple.cpp:56]  Condition h_array[i] != 3*i failed 
[OMPVV_INFO: test_target_enter_exit_data_classes_simple.cpp:122] Test is running on device.
[OMPVV_INFO: test_target_enter_exit_data_classes_simple.cpp:94] Testing simple class mapping
[OMPVV_INFO: test_target_enter_exit_data_classes_simple.cpp:128] The value of errors is 999.
[OMPVV_RESULT: test_target_enter_exit_data_classes_simple.cpp] Test failed on the device.
```

The value of h_array in line 56 is still `i` (as if the copy never happened. 

Any thoughts?

**Comment by josemonsalve2** [comment]
Ah! Nevermind. I just realized I kept running it with clang++ always. I was changing CC instead of CXX... This passes on GCC and XLC, it fails on Coral Clang

**Comment by josemonsalve2** [comment]
I've created a PR @dmcdougall, feel free to add any comment! Sorry for the delay!
