### ISSUE TITLE
LICENSE confusion

### ISSUE THREAD

**Issue by bernhold** [SOLLVE/sollve_vv#172]
Reported to @bernhold by @arm-chrjan01

**Describe the bug**
https://github.com/SOLLVE/sollve_vv/blob/master/LICENSE says BSD 2-clause at the top, but the content of the license is 3-clause.  The same appears on the UDel web site: https://crpl.cis.udel.edu/ompvvsollve/license/

See https://opensource.org/licenses/BSD-3-Clause and https://opensource.org/licenses/BSD-2-Clause for correct versions.

**Expected behavior**
License title and content should be consistent, all web relevant web pages should be updated accordingly.

**Comment by spophale** [comment]
I went back to check what ORNL had said when they had approved our Open Source Copyright, they had said either of the BSD would do. They had provided the BSD-3. We will correct the BSD-2 mentions to BSD-3.

**Comment by spophale** [comment]
See #173
