### ISSUE TITLE
Possible bug in 4.5/target_data/test_target_data_map_devices

### ISSUE THREAD

**Issue by estewart08** [SOLLVE/sollve_vv#176]
**Describe the bug**
I believe this bug affects other tests as well, but I will target only one for this review.

Using AOMP 11.7-0, test_target_data_map_set_default_device.F90 will pass on single GPU but not on machines with 2+ GPUs. I wanted to open up a discussion on a possible fix to see what your thoughts are. I believe the issue is with the target data not copying back the 'anArray' to host before moving on to the next devData (target data) increment. Therefore, the next GPU, say number 1, does not get the previously incremented array and sees all 1's instead of 2's. This may be due to when we reach the end of the devComp inner loop we are not in the same data environment as the devData. 

The focus is on the test_set_default_device() function:
```
            ! Initialize the array
            anArray(:) = 1

            ! Iterate over all the devices
            DO devData = 0, num_dev - 1
              ! set default device
              call omp_set_default_device(devData)
              !$omp target data map(tofrom: anArray(1:N))

                ! Iterate over all the devices doing comp
                ! to guarantee that the right data env is
                ! being copied back and forth
                DO devComp = 0, num_dev - 1
                  call omp_set_default_device(devComp)
                  !$omp target map(alloc: anArray(1:N))
                    ! When on other devices different to the 
                    ! default device of the target data region
                    ! this operation would not be reflected on the host
                    IF (devComp == devData) THEN
                      anArray(1:N) = anArray(1:N) + 1
                    END IF

                  !$omp end target
                END DO !devComp
                call omp_set_default_device(devData)  <--- my proposal to fix the issue
              !$omp end target data
            END DO !devData
```
Let's run through the logic here for a dual GPU machine to see if I am understanding this right:
```
devData = 0
call omp_set_default_device(devData)  ! default device is 0
---Begin Target Data Region map(tofrom: anArray(1:N)---
  devComp = 0
    call omp_set_default_device(devComp)  ! default device is 0
    ---Target Region---
      devComp == DevData
        increment anArray
    ---End Target Region---
  devComp = 1
    call omp_set_default_device(devComp)  ! default device is 1
    ---Target Region---
   devComp /= DevData
      do nothing to anArray
    ---End Target Region---
---End Target Data Region--- <--- a copy to host should be here from device 0 right?
 devData = 1
 ...
```
At the end of the first data region we still have default_device = 1, due to the inner loop. I do not see a copy from target to host for anArray as the array is still all 1's on the host. The tests expects the next GPU to get anArray with the +1 incremented values (2). 

**So my question is when the inner loop finishes, does being in a different default device than the outer loop prevent/confuse the copy to host?** I believe we need to set the default_device back to devData so the copy to host can occur. Trying to determine if this is a test or an AOMP compiler issue where we are not adhering to the spec. See the first code block for the possible fix. Thanks!

--------------------------------------------------
**Test that it applies to**
4.5/target_data/test_target_data_map_devices.F90

**To Reproduce**
1. Go to https://github.com/ROCm-Developer-Tools/aomp/releases/tag/rel_11.7-0 and download correct AOMP version for your OS.
2. Install rpm or debian of your choice.
3. ***Set your path to AOMP and march value correctly!***
make VERBOSE=1 VERBOSE_TESTS=1 LOG=1 LOG_ALL=1 FC='/path-to-aomp/aomp_11.7-0/bin/flang -fopenmp -fopenmp-targets=amdgcn-amd-amdhsa -Xopenmp-target=amdgcn-amd-amdhsa -march=<your_gpu_arch>' all SOURCES=tests/4.5/target_data/test_target_data_map_devices.F90

[header test_target_data_map_devices.F90:86]  Condition condition failed
[header test_target_data_map_devices.F90:37]  Condition condition failed
Libomptarget fatal error 1: failure of target construct while offloading is mandatory

**Expected behavior**
Test expected to pass on single and multi GPU machines.

**Compiler**
AOMP 11.7-0
**Accelerator hardware**
Failed with 2 gfx900s and  4 gfx906s.

**Comment by jprotze** [comment]
The proposed fix does not have any impact to the test. The mapping of a target data region is evaluated at the beginning of the region. Changing the default device later has no impact on the mapping.

**Comment by estewart08** [comment]
Thanks for the response, as of right now I am leaning toward a fix in our compiler, will close this issue.
