### ISSUE TITLE
Fortran `declare target` tests

### ISSUE THREAD

**Issue by simoatze** [SOLLVE/sollve_vv#191]
Hi all.

I was wondering if you have a plan to expand testing of `declare target` for Fortran, I see there is currently only one test.

Thanks!
Simone

**Comment by spophale** [comment]
Hi Simone,
Did you have a particular use-case in mind ?

**Comment by tmh97** [comment]
Hey @simoatze, we now have 3 different tests for declare target. Are there any other aspects of declare target you would like to see implemented?

**Comment by simoatze** [comment]
Hi @tmh97, yes I have finally updated the suite and those tests look good. If I come up with new ones I'll share them. Thank you!
