### ISSUE TITLE
[Invalid syntax] 5.0/declare_target/test_declare_target_nested.c: Spurious '{'

### ISSUE THREAD

**Issue by tob2** [SOLLVE/sollve_vv#195]
The file `5.0/declare_target/test_declare_target_nested.c` has:
```C
#pragma omp parallel for 
{
  for (i = 0; i < N; i++) {
```

In accordance with the OpenMP spec, GCC rejects this code with:
```
./tests/5.0/declare_target/test_declare_target_nested.c:35:1: error: for statement expected before ‘{’ token
   35 | {
      | ^
```

The OpenMP 5.0 requires _for-loops_ and the upcoming spec a _loop-nest_; however, '{' is neither.

**Comment by tmh97** [comment]
Associated PR has been merged, thanks!
