### ISSUE TITLE
Illegal use of "ANY" function in test_target_enter_data_allocate_array_to.F90

### ISSUE THREAD

**Issue by simoatze** [SOLLVE/sollve_vv#2]
At lines 73, 108, and 144 the function ANY is used with an integer array while it expects a logical array.

**Comment by Meinersbur** [comment]
Hi and thank you for filing the issue,

this is only a mirror of the official repository. Could you report the issue at the official repository: https://bitbucket.org/crpl_cisc/sollve_vv/issues?status=new&status=open ?

**Comment by simoatze** [comment]
Will do for both issues reported. Thanks!

**Comment by Meinersbur** [comment]
Thank you!
