### ISSUE TITLE
Non-conforming map clause in test_target_data_use_device_addr.c

### ISSUE THREAD

**Issue by jacobdweightman** [SOLLVE/sollve_vv#204]
test_target_data_use_device_addr.c contains the following code:
```
#pragma omp target data map(to: device_data) use_device_addr(device_data)
{
    int *dev_ptr;
    dev_ptr = &device_data;
#pragma omp target map(to:device_data) map(tofrom: errors) map(from: host_data) is_device_ptr(dev_ptr)
    {
        if(&device_data != dev_ptr)
            errors++;
    }
}
```

Regarding `use_device_addr` clauses on `target data` constructs (2.12.2), the OpenMP 5.0 specification says
> List items that appear in a `use_device_addr` clause have the address of the corresponding object in the device data environment inside the construct. For objects, any reference to the value of the object will be to the corresponding object on the device, while references to the address will result in a valid device address that points to that object.

Since the `device_data` in the `map` clause on the `target` construct occurs inside of the `target data` construct, it ought to refer to the device copy created by the `target data` directive. Furthermore, in the description of the `map` clause (2.19.7.1), the specification says
> If the `map` clause appears on a `target`, `target data`, or `target enter data` construct then on entry to the region the following sequence of steps occurs as if performed as a single atomic operation:
> 1. If a corresponding list item of the original list item is not present in the device data environment, then:
>     a) A new list item with language-specific attributes is derived from the original list item and created in the device data environment
>.   b) ...

Since the copy of `device_data` on the device is the list item in the map clause, and that list item has no corresponding item in the device data environment (it is a variable on the device, after all!), another distinct `device_data` may be created in the device data environment. Since the `device_data` from the `target data` construct and the `device_data` in the `target` construct may be distinct variables, it seems that the assertion inside of the `target` region may fail for a conforming implementation.

**Comment by tob2** [comment]
Isn't this essentially the same as my Issue #187, which has the pending Pull Request #193?

**Comment by jacobdweightman** [comment]
You're absolutely right. I'll close the issue.
