### ISSUE TITLE
Need "#pragma omp taskwait" in target and task nowait

### ISSUE THREAD

**Issue by jhdavis8** [SOLLVE/sollve_vv#219]
Need "#pragma omp taskwait" before this line. @spophale could you fix this?

_Originally posted by @ye-luo in https://github.com/SOLLVE/sollve_vv/pull/190#discussion_r502000181_

**Comment by ye-luo** [comment]
Could also consider renaming the file.
"test_target_nowait_and_task.c" instead of "test_target_and_task_nowait.c"

**Comment by spophale** [comment]
[#220 ](url)
