### ISSUE TITLE
Allow the user to select NUM_THREADS and NUM_TEAMS for the tests that use this

### ISSUE THREAD

**Issue by josemonsalve2** [SOLLVE/sollve_vv#22]
**The problem**
Not all the devices would support large number of threads. In order to avoid being GPU specific we need to be flexible with respect to the requested number of threads. This is somehow different to the OpenMP Environment variables as we don't want to depend on the implementation, but rather pass the information from the test suite to OpenMP.

List of tests that this applies to:
- [x] test_target_firstprivate
- [x] test_target_private
- [x] test_target_teams_distribute_firstprivate
- [x] test_target_teams_distribute_num_teams
- [x] test_target_teams_distribute_private
- [x] test_target_teams_distribute_shared
- [x] test_target_teams_distribute_collapse
- [x] test_target_teams_distribute_thread_limit
- [x] test_target_teams_distribute_dist_schedule
- [x] test_target_teams_distribute_default_none
- [x] test_target_teams_distribute_default_shared
- [x] test_target_teams_distribute_default_private
- [x] test_target_teams_distribute_default_firstprivate
- [x] test_target_teams_distribute_parallel_for
- [x] test_target_teams_distribute_parallel_for_firstprivate
- [x] test_target_teams_distribute_parallel_for_if_no_modifier
- [x] test_target_teams_distribute_parallel_for_if_parallel_modifier
- [x] test_target_teams_distribute_parallel_for_if_target_modifier
- [x] test_target_teams_distribute_parallel_for_num_teams
- [x] test_target_teams_distribute_parallel_for_num_threads
- [x] test_target_teams_distribute_parallel_for_private
- [x] test_target_teams_distribute_parallel_for_schedule_private
- [x] test_teams
- [x] test_teams_distribute_default_none

**Describe the solution you'd like**
Create a new set of options to be included in the Makefile/system File:
* `OMPVV_NUM_THREADS_DEVICE`
* `OMPVV_NUM_TEAMS_DEVICE`
* `OMPVV_NUM_THREADS_HOST`

These variables are sent to the source codes through -D option in the compiler line, and used everywhere we have num_teams and num_threads. Some cases will have to require special attention. Specially those where we are trying to test for the num_threads and num_teams clauses themselves. 

We probably want to also have a set of default values. These values should live in ompvv.h header files. 

**Additional context**
This request was a consequence of the discussion occurred in Issue #15

**Comment by jhdavis8** [comment]
List of tests that this applies to:
- [ ] test_target_firstprivate
- [ ] test_target_private
- [ ] test_target_teams_distribute_firstprivate
- [ ] test_target_teams_distribute_num_teams
- [ ] test_target_teams_distribute_private
- [ ] test_target_teams_distribute_shared
- [ ] test_target_teams_distribute_parallel_for
- [ ] test_target_teams_distribute_parallel_for_firstprivate
- [ ] test_target_teams_distribute_parallel_for_if_no_modifier
- [ ] test_target_teams_distribute_parallel_for_if_parallel_modifier
- [ ] test_target_teams_distribute_parallel_for_if_target_modifier
- [ ] test_target_teams_distribute_parallel_for_num_teams
- [ ] test_target_teams_distribute_parallel_for_num_threads
- [ ] test_target_teams_distribute_parallel_for_private
- [ ] test_target_teams_distribute_parallel_for_schedule_private

**Comment by jhdavis8** [comment]
When PRs #205 and #206 are merged, this will be done.
