### ISSUE TITLE
Document how to port to a new platform

### ISSUE THREAD

**Issue by bernhold** [SOLLVE/sollve_vv#234]
**Is your feature request related to a problem? Please describe.**
Documentation enhancement

**Describe the solution you'd like**
It would be nice to have a section documenting, step by step, what is needed to add a new platform (compiler, device, machine)

**Comment by josemonsalve2** [comment]
I want to mention that the documentation for this is in the website:
https://crpl.cis.udel.edu/ompvvsollve/documentation/newsystem/

However, we should do something about the wiki. This also applies to issue #233

**Comment by bernhold** [comment]
Okay, but that's not where the README.md in the repo points me to.

IMHO, one place is fine, as long as the documentation is up to date and other resources point you to the right place! :-)

**Comment by spophale** [comment]
The website link in the README.md takes me to landing page with has https://crpl.cis.udel.edu/ompvvsollve/documentation/newsystem/ as one of the links. 
Only thing missing there is Fortran specifics. 

I will edit README.md to be more explicit.
