### ISSUE TITLE
Complex templated test in C++

### ISSUE THREAD

**Issue by josemonsalve2** [SOLLVE/sollve_vv#24]
**Directive and clause it applies to**
Class created inside target region which is constructed through complex templates. It should apply to the target directive.

**Specification details**
This test was taken from: https://bugs.llvm.org/show_bug.cgi?id=43771
This test is from Alpaka, and it could go inside the application tests folder

**Pseudocode**
```C++
#include <type_traits>

template<int Dim>
struct V {
  template<
    bool B = (Dim == 0),
    typename = typename std::enable_if<B>::type>
  V() {}

  template<
    typename TArg0,
    typename = typename std::enable_if<
        (std::is_same<unsigned long, typename std::decay<TArg0>::type>::value)
       >::type>
  V(TArg0 && arg0) {}
};

template<int Dim>
struct S {
  V<Dim> v;
};

int main(int argc, char *argv[]) {
  #pragma omp target
  {
    S<0> s;
  }

  return 0;
}
```

**Comment by jhdavis8** [comment]
See PR #76
