### ISSUE TITLE
Invalid "map(delete:" for "target data" and "target"

### ISSUE THREAD

**Issue by tob2** [SOLLVE/sollve_vv#242]
From https://gcc.gnu.org/pipermail/gcc-patches/2021-January/563167.html

The following affects `5.0/target/test_target_mapping_before_delete.c` which uses `omp target ... map(delete:`.

"In *OpenMP 5.0,* I certainly see the *target data*:
> [163:16] A map-type in a map clause must be to, from, tofrom or alloc.

"restriction and similarly for *target*:

> [174:27] A map-type in a map clause must be to, from, tofrom or alloc.
restriction.

"*OpenMP 4.5* has those restrictions in [97:15] and [106:13]."

This shows up at:

```
5.0/target/test_target_mapping_before_delete.c:#pragma omp target map (to: scalar, a, member) map (from: x, y, z) map(delete: scalar, a, member)
5.0/target/test_target_mapping_before_delete.c:#pragma omp target map (tofrom: scalar, c, member) map (from: x, y, z) map (delete: scalar, c, member)
```

**Comment by tob2** [comment]
Patch would be the following – but the question is whether the testcase should be removed for good as already the name `test_target_mapping_before_delete` does not make sense without the `delete:`.

Or, alternatively, change `before_delete` to `before_from` (file name, comments and function names)?

```diff
--- a/tests/5.0/target/test_target_mapping_before_delete.c
+++ b/tests/5.0/target/test_target_mapping_before_delete.c
@@ -42 +42 @@ int to_before_delete () {
-#pragma omp target map (to: scalar, a, member) map (from: x, y, z) map(delete: scalar, a, member)
+#pragma omp target map (to: scalar, a, member) map (from: x, y, z)
@@ -81 +81 @@ int to_from_before_delete(){
-#pragma omp target map (tofrom: scalar, c, member) map (from: x, y, z) map (delete: scalar, c, member)
+#pragma omp target map (tofrom: scalar, c, member) map (from: x, y, z)
```

**Comment by spophale** [comment]
Thanks @tob2 ! 
It looks like delete is only allowed on target exit data as per 5.0.  I propose to edit the test to use target enter - exit and remove from under target.

**Comment by spophale** [comment]
Addressed.
