### ISSUE TITLE
User request to provide an option to run all tests in the same run.

### ISSUE THREAD

**Issue by spophale** [SOLLVE/sollve_vv#270]
**Describe the solution you'd like**
Provide an option to run all (currently 4.5 and 5.0 )tests in the same run.

**Additional context**
Currently OMP_VERION decides which tests are run.

**Comment by tob2** [comment]
I think that would be useful, but the output should make it simpler to distinguish different versions. Currently, grepping for the output, it just shows the test name - and the names between 4.5 and 5.0 are not unique and, even if they were, it would be useful to know the OMP_VERSION.

Hence, we run the testsuite twice - once with LOGDIR = log-4.5 + BINDIR = bin-4.5 and once with log-5.0 + bin-5.0.

One possibility would be to prefix the files in logs + bin dirs with the OMP_VERSION.

**Comment by spophale** [comment]
Yes, we are aware of the issues here. Maybe the simplest solution would be to provide the path as the unique identifier. Need to think a bit more.
