### ISSUE TITLE
Move 4.5 to 5.0 for tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_collapse.c

### ISSUE THREAD

**Issue by tob2** [SOLLVE/sollve_vv#273]
I think `test_target_teams_distribute_parallel_for_collapse.c` is not valid for OpenMP 4.5 but only for OpenMP 5.0;
https://github.com/SOLLVE/sollve_vv/blob/master/tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_collapse.c

Namely, I believe the  'k = i' in the following makes it a nonrectangular loop nest:

```C
#pragma omp target teams distribute parallel for collapse(4) map(tofrom: a) private(i,j,k,l)
  for (i = 0; i < SIZE_N; i++) {
    for (j = 0; j < SIZE_M; j++) {
      for (k = i; k < SIZE_N; k++) {
        for (l = 0; l < SIZE_M; l++) {
          a[i][j][k][l] += i+2*j+3*k+4*l;
```

And as OpenMP 5.0 states, new in 5.0 is:
> The canonical loop form was defined for Fortran and, for all base languages, extended to permit27non-rectangular loop nests (see Section 2.9.1 on page 95).

Thus, I think it should be moved from the `4.5` to the `5.0` directory.

**Comment by spophale** [comment]
Good catch. Will move it. Thanks!
