### ISSUE TITLE
omp_get_max_threads computed in a target region may defer from the one calculated in a different target region

### ISSUE THREAD

**Issue by simoatze** [SOLLVE/sollve_vv#281]
Hi guys,

I came across a possible issue in the test [test_target_parallel.c](https://github.com/SOLLVE/sollve_vv/blob/c6fa62ee42a273e026a69bc4e9ef2da85a909801/tests/4.5/target_parallel/test_target_parallel.c)

With both NVIDIA HPC SDK and Clang/LLVM this assertion [scalar_num_threads > max_threads](https://github.com/SOLLVE/sollve_vv/blob/c6fa62ee42a273e026a69bc4e9ef2da85a909801/tests/4.5/target_parallel/test_target_parallel.c#L57) fails. I believe the number of threads can be different across different target regions as the grid size can be implementation dependent and it is also influenced by the register usage.

A possible solution could be to use teams and set `num_teams` and `num_threads` clauses.

What do you think?

Thanks!
Simone

**Comment by jhdavis8** [comment]
I remember Jose brought this question up on the OMP mailing list back when we were working on the test. Here's what we got from Deepak Eachempati (Cray) on this question:

> I think this is the relevant passage:
> 
> > When a target task executes a target region, the generated initial task uses the values of the data environment scoped ICVs from the device data environment ICV values of the device that will execute the region. 
> 
> The device data environment has a single copy of each of the data environment scoped ICVs, which cannot be directly modified by user code. That is what is used to initialize the ICV in the data environment of each target region’s initial task.
> 
> So while the ICV for nthreads-var is implementation defined, I do think the spec guarantees that the initial value should be the same from one target region to the next.
> 
> -- Deepak

I see your point, however, as it would make sense for the implementation to have some flexibility in choosing the grid size based on register usage. It's just a matter of what the spec demands. @josemonsalve2 @spophale what do you think?

**Comment by spophale** [comment]
IMO though it is unlikely that the number of threads will change between regions, the spec allows it, or rather does not pose any such restrictions. The test should use OMPVV variables and not make assumptions about the env.

**Comment by simoatze** [comment]
@spophale Do you mean the test should set correctly the OMPVV variables or when I run the test should I use them? For the second case how am I supposed to use the env variable, would you point me to an example? Thanks!

**Comment by spophale** [comment]
Going back to the specific test; I don't see a particular need to test max threads and number of threads in different regions. That change, when in, will circumvent the current issue. 
Generally, in the test suite header file we have env variables like OMPVV_NUM_THREADS_DEVICE  and OMPVV_NUM_THREADS_HOST set and we are using them more diligently in the feature tests. I would suggest you look to see if the default numbers suit your architecture and change for specific runs, if needed. 
Also, if you find (older) tests that could use the env(s) but don't, feel free to create an Issue (or submit a PR).
