### ISSUE TITLE
test_taskloop_in_reduction.c: Invalid specification of same variable in multiple data-sharing clauses

### ISSUE THREAD

**Issue by tob2** [SOLLVE/sollve_vv#296]
The two testcases below use `sum` **twice** in **data-sharing** clauses: `reduction(task, +: sum)` and `shared(sum)`.

Namely: 

* `tests/5.0/taskloop/test_taskloop_in_reduction.c` (line 32) has
```C
#pragma omp parallel reduction(task, +: sum) num_threads(OMPVV_NUM_THREADS_HOST) shared(y, z, num_threads, sum)
```
* and likewise `tests/5.0/taskloop/test_taskloop_in_reduction_device.c` (line 33)
```C
#pragma omp target parallel reduction(task, +: sum) num_threads(OMPVV_NUM_THREADS_DEVICE) shared(y, z, num_threads, sum) defaultmap(tofrom)
```
The OpenMP specification specifies (here OpenMP 5.1) under `2.21.4  Data-Sharing Attribute Clauses`:
>  A list item may not appear in more than one clause on the same directive, except that it may be specified in both `firstprivate` and `lastprivate` clauses.

I additionally note that `2.21.5  Reduction Clauses and Directives` starts with: _“The reduction clauses are data-sharing attribute clauses”._

 * * *
**Hence,** I think this usage is **invalid** – and GCC also rejects both testcase with: `error: ‘sum’ appears more than once in data clauses`

**Comment by spophale** [comment]
@tob2 In 5.0 it explicitly states that "A list item that appears in a reduction clause of a worksharing construct must be shared in
31 the parallel region to which a corresponding worksharing region binds." Pg 301,ln 30. 

I cannot find the statement "A list item may not appear in more than one clause on the same directive.." in 5.0.

**Comment by jhdavis8** [comment]
Reopening because of other tests with the same issue
