### ISSUE TITLE
Does `test_target_private` contain a race condition?

### ISSUE THREAD

**Issue by dmcdougall** [SOLLVE/sollve_vv#31]
Here is a shortened version of the test case:

```fortran
#include "ompvv.F90"

#define NUM_THREADS 10

      PROGRAM test_target_private
        USE iso_fortran_env
        USE ompvv_lib
        USE omp_lib
        implicit none
        INTEGER :: i, j
        INTEGER :: compute_array(NUM_THREADS)
        INTEGER :: actualThreadCnt = 0
        INTEGER :: p_val, fp_val

        compute_array(:) = 0

        CALL omp_set_num_threads(NUM_THREADS)

        !$omp parallel private(p_val, fp_val) shared(actualThreadCnt)
          fp_val = omp_get_thread_num() + 2
          p_val = omp_get_thread_num() + 1
          actualThreadCnt = omp_get_num_threads()
          !$omp target map(tofrom:compute_array) map(to:fp_val) private(p_val)
            p_val = fp_val - 1
            compute_array(p_val) = 100
            p_val = p_val + 99
          !$omp end target
          IF (p_val == omp_get_thread_num() + 1) THEN
            write (*,*) "thread ", p_val, " is doing the right thing. \
            array val is ", compute_array(p_val)
            compute_array(p_val) = compute_array(p_val) + 1
          END IF
        !$omp end parallel

        do i=1,NUM_THREADS
            write (*,*) i
            write (*,*) compute_array(i)
        enddo

        OMPVV_TEST_VERBOSE(ANY(compute_array(:) /= 101))

      END PROGRAM test_target_private
```

**Describe the bug**

I am concerned about this part of the test:

```fortran
        !$omp parallel private(p_val, fp_val) shared(actualThreadCnt)
          fp_val = omp_get_thread_num() + 2
          p_val = omp_get_thread_num() + 1
          actualThreadCnt = omp_get_num_threads()
          !$omp target map(tofrom:compute_array) map(to:fp_val) private(p_val)
```

1. The parallel region defaults to the `shared` data-sharing attribute for the `compute_array` variable, so each thread sees the same `compute_array` data;
2.  The target region then forces each thread to make a copy with `map(tofrom:compute_array)`;
3.  So as a result of 2., each launched kernel contains its own private `compute_array` data;
4.  Each launched kernel modifies a _piece_ of compute array;
5.  `compute_array` is copied back to the host, almost certainly overwriting data elements modified by kernels launched by other host threads. 

**Test that it applies to**
`test_target_private`

**To Reproduce**

`make VERBOSE=1 VERBOSE_TESTS=1 LOG=1 LOG_ALL=1 CC=gcc CXX=g++ FC=gfortran all SOURCES=test_target_private.F90` gives a test failure

**Expected behavior**

Well, I guess with a data race the expected behaviour *is* a test failure :)  I'm arguing that the test has a bug.

**Compiler**
The [CodeBench Sourcery Lite Edition](https://go.mentor.com/cblite) compiler (a fork of GCC).

**Accelerator hardware**
AMD MI50 GPU

**Comment by josemonsalve2** [comment]
@dmcdougall yes, you are right, there's also technically a race in the `actualThreadCnt`, which might be better to protect as well. 

Sorry for the late response, we're getting through the pre-SC preparation madness. I will take a look at this and fix it.

**Comment by dmcdougall** [comment]
Ok.  Yeah there's no rush and it's no problem.  I was trying to understand whether it was a compiler bug (not too unlikely given the Mentor Graphics folks are implementing new functionality) or a bug in the test.  And the test took a while to read just because there's quite a bit going on in not many lines of code.

I'll also be at SC if you want to meet up.

**Comment by josemonsalve2** [comment]
Definitely! Let's meet up

**Comment by estewart08** [comment]
I was looking at the C version of test_target_private and observe the same issue. Could that map clause look something like this:
```
 map(tofrom:compute_array[fp_val][0:N])
```

**Comment by tob2** [comment]
Besides the data race in copying the data to and from the device, I think the following line is also wrong:
```OMPVV_TEST_VERBOSE(ANY(compute_array(:,1:actualThreadCnt) /= 101))```
I think the `:` and the `1:actualThreadCnt` have to be reversed.

That `compute_array` variable is set to the following, where `p_val` is `omp_get_thread_num() + 1`
```
                compute_array(p_val,:) = 100
                p_val = p_val + 99
…
                compute_array(p_val,:) = compute_array(p_val,:) + 1
```

**Comment by spophale** [comment]
Thanks @tob2 and @estewart08 for pointing out the bug(s). I was thinking about moving the parallel inside target to avoid race/overwrites.

**Comment by spophale** [comment]
See #135 .

**Comment by tob2** [comment]
The **C version** of the test case as been **fixed** in Pull Req. #136 (merged in commit 9e4b0f97c4336c29e886a359324ad1b8924f9c26, which is an alternative approach to Pull Req. #135).

However, the Fortran test case has **still** the copy-out **race condition**  (+ "(p_val,:)" vs. "(:,p_val)" issue).

**Comment by spophale** [comment]
See #144

**Comment by jhdavis8** [comment]
#144 has been pushed.
