### ISSUE TITLE
Verify tests/4.5/target_data/test_target_data_map_devices.F90

### ISSUE THREAD

**Issue by spophale** [SOLLVE/sollve_vv#333]
**Describe the bug**
Mapping errors. Fails with IBM XL compiler.

**Test that it applies to**
tests/4.5/target_data/test_target_data_map_devices.F90

**To Reproduce**
Compile:
`xlf_r -I/ccs/home/swaroop/SOLLVE/sollve_vv/ompvv -qsmp=omp -qoffload test_target_data_map_devices.F90 -o ttdmd`

Run:
`./ttdmd`

Error:
`Encountered a map that partially includes the memory of a prior map on the target device 0. The encountered map starts at host address 0x7fffc570e5e0 and the prior map starts at host address 0x7fffc570e5d0.  The program will stop.`

**Expected behavior**
Test should pass.

**Compiler**
IBM XL (xlf_r)

**Accelerator hardware**
Summit

**Comment by od102** [comment]
Run on Summit with default IBM XL (Fotran) compiler both using a single and multiple GPUs and getting
`[OMPVV_RESULT test_target_data_map_devices.F90] Test passed on the device.`
is there anything I might be missing?

**Comment by od102** [comment]
Passes fine with NVHPC/21.3 on Summit as well.
