### ISSUE TITLE
Fortran tests failing on Spock

### ISSUE THREAD

**Issue by spophale** [SOLLVE/sollve_vv#334]
Applies to:

- [ ] test_target_data_map_set_default_device.F90.o: FAIL. exit code: 1
- [ ] test_target_enter_data_devices.F90.o: FAIL. exit code: 1
- [ ] test_target_enter_data_set_default_device.F90.o: FAIL. exit code: 1
- [ ] test_target_enter_exit_data_devices.F90.o: FAIL. exit code: 1
- [ ] test_target_enter_exit_data_set_default_device.F90.o: FAIL. exit code: 1

Need to verify if there are potential mapping issues in the tests.

**Comment by tmh97** [comment]
@spophale Curious which compiler is throwing errors. I ran all these tests with gcc/10.2.0 gfortran on summit without issues. On Tulip, cray fortran (ftn) compiler had issues with the 'device' clause for all tests

**Comment by spophale** [comment]
Right, I noticed that as well. This is CCE (with rocm/4.1.0). For example, the devices test passes with GNU because it sees only 1 device. When multiple devices are detected it fails.

**Comment by tmh97** [comment]
Same as tulip, "OpenMP 4.0 "device" clause is being ignored."

**Comment by od102** [comment]
checked the first example above, it's conformant. (and confirming that cce does not support multi device).

**Comment by od102** [comment]
all five of these tests pass with both nvhpc and xl, using both single and multiple devices.
