### ISSUE TITLE
No explicit map for array in 4.5 version of target reduction tests

### ISSUE THREAD

**Issue by fzou1** [SOLLVE/sollve_vv#339]
**Describe the bug**
No explicit map for array in 4.5 version of target reduction tests

**Test that it applies to**
Tests related to target reduction under sollve_vv/tests/4.5/target_teams_distribute folder (https://github.com/SOLLVE/sollve_vv/tree/master/tests/4.5/target_teams_distribute). For example, the omp directive in test_target_teams_distribute_reduction_and.c:

_#pragma omp target teams distribute reduction(&&:result) defaultmap(tofrom:scalar)
    for (int x = 0; x < N; ++x) {
      num_teams[x] = omp_get_num_teams();
      result = result && a[x];
    }_

**To Reproduce**
N/A

**Expected behavior**
Add explicit map for array as in 5.0 version of tests.

**Compiler**
N/A

**Accelerator hardware**
N/A

**Comment by fzou1** [comment]
> offloading

g

**Comment by spophale** [comment]
@fzou1  OMP 4.5 spec,Pg 216, lines 9-10 - "If a variable is not a scalar then it is treated as if it had appeared in a map clause with a map-type of tofrom."

From the V&V perspective it is interesting to have slightly different tests even for the same features.

**Comment by spophale** [comment]
@fzou1 with your consent, I would like to close this issue.

**Comment by fzou1** [comment]
Thank you for the explanation. Closed.
