### ISSUE TITLE
Several 4.5 Failing with GCC

### ISSUE THREAD

**Issue by tmh97** [SOLLVE/sollve_vv#356]
Investigate and determine whether tests need modification or whether bug reports need to be submitted.

- [ ] test_taget_teams_distribute_reduction_and.c 
- [ ] test_target_teams_distribute_reduction_or.c
- [ ] test_target_teams_distribute_if.F90
- [ ] test_target_teams_distribute_lastprivate.F90

**Comment by tob2** [comment]
Just looking at the log files for GCC mainline (GCC 12) on x86-64-gnu-linux with nvptx offloading:
* all 4.5 + 5.0 tests starting with `test_target_teams_*` PASS
* as does `qmcpack_target_math.c`.

For combined constructs, there were some fixes recently in GCC – and in the OpenMP spec, which might affect the result. At least for the `target ... reduction` and possible `target ... lastprivate`. No idea about the `if` one.

_I don't know whether it is a version problem (your GCC being too old and it is now fixed) – or some platform dependent issue or some race condition. – I also did not check old log files to see whether the FAIL disappeared or it keeps flipping between PASS and FAIL._
