### ISSUE TITLE
Add test for target with the in_reduction clause

### ISSUE THREAD

**Issue by tmh97** [SOLLVE/sollve_vv#374]
Create a target/device version of this test

**Comment by tmh97** [comment]
Instead of creating a `target taskloop in_reduction` test, we will need to create a `target in_reduction` test. It was pointed out that target taskloop is not a valid combined construct.

**Comment by mjcarr458** [comment]
Should this issue be closed by [5.0 target in_reduction test](https://github.com/SOLLVE/sollve_vv/blob/master/tests/5.0/target/test_target_in_reduction.c)?
