### ISSUE TITLE
test_target_enter_data_global_array.c missing include

### ISSUE THREAD

**Issue by estewart08** [SOLLVE/sollve_vv#375]
**Describe the bug**
tests/4.5/target_enter_data/test_target_enter_data_global_array.c is missing:
#include "ompvv.h"

**Test that it applies to**
tests/4.5/target_enter_data/test_target_enter_data_global_array.

**To Reproduce**
make VERBOSE=1 VERBOSE_TESTS=1 LOG=1 LOG_ALL=1 CC='clang -fopenmp -fopenmp-targets=amdgcn-amd-amdhsa -Xopenmp-target=amdgcn-amd-amdhsa -march=gfx906' all SOURCES=tests/4.5/target_enter_data/test_target_enter_data_global_array.c

sollve_vv/tests/4.5/target_enter_data/test_target_enter_data_global_array.c:25:2: error: use of undeclared identifier 'OMPVV_TEST_OFFLOADING'
 OMPVV_TEST_OFFLOADING;

**Expected behavior**
Passing test.

**Compiler**
AOMP 13.0-5

**Accelerator hardware**
gfx906

**Comment by tmh97** [comment]
Reproduced, went ahead and fixed in latest PR linked here. Thank you!
