### ISSUE TITLE
tests/5.0/target/test_target_device.c does not follow the OpenMP 5.0 specification (ancestor restrictions)

### ISSUE THREAD

**Issue by marvol77** [SOLLVE/sollve_vv#393]
The function `test_target_device_ancestor` in the file `tests/5.0/target/test_target_device.c` uses a `target` directive with the device-modifier `ancestor` which was introduced in OpenMP 5.0.

The [specification of OpenMP 5.0](https://www.openmp.org/wp-content/uploads/OpenMP-API-Specification-5.0.pdf) (and also OpenMP 5.1) states the following restrictions when using `ancestor` (p. 174f):

> If a device clause in which the ancestor device-modifier appears is present on the construct, then the following restrictions apply:
> – A requires directive with the reverse_offload clause must be specified;
> [...]
> – No OpenMP constructs or calls to OpenMP API runtime routines are allowed inside the corresponding target region.

Thus, it should be added `#pragma omp requires reverse_offload` and the usage of the OpenMP API runtime routine `omp_is_initial_device()` is not allowed. Otherwise a compile error can be expected for the test. 

The second issue holds also for `tests/5.0/requires/test_requires_reverse_offload.c` where `omp_is_initial_device` is indirectly (via `host_function`) used in the target region of the `#pragma omp target device(ancestor:1)` construct.

**Comment by tob2** [comment]
Question: Is there still something to solve or not?

I see two PR which are both merged, #394 (test_target_device.c) and #396 (test_requires_reverse_offload.c)

Is there anything else? If not, can this issue be closed?

**Comment by tmh97** [comment]
@tob2 this is solved, closing this issue now. Thank you for checking in on this !
