### ISSUE TITLE
error: OpenMP runtime API call ‘int omp_get_thread_num()’ strictly nested in a ‘teams’ region

### ISSUE THREAD

**Issue by tob2** [SOLLVE/sollve_vv#417]
### ISSUE: OpenMP only permits two API routines in strictly nested in a `teams` – but other routines are invoked.

Solution: Either wrap those calls in a permitted region like `parallel` or `distribute` or `loop`, remove them outside `teams` (but note that for a `teams` nested in `target` nothing else is permitted in the target region except for the `teams` region), or remove the API call completely.

The error messages below are obtained with GCC 12, which added the check for the API routine call.

OpenMP has (here 5.2 wording) has in "10.2 `teams` Construct".

> Restrictions to the `teams` construct are as follows:
>
> * [...]
> * `distribute` regions, including any distribute regions arising from composite constructs, `parallel` regions, including any `parallel` regions arising from combined constructs, `loop` regions, `omp_get_num_teams()` regions, and `omp_get_team_num()` regions are the only OpenMP regions that may be strictly nested inside the `teams` region.

### Errors reported by GCC

* https://github.com/SOLLVE/sollve_vv/blob/b87d5ef85192c56bbcd8fdeaab87eb1bbe2c1bb1/tests/5.0/loop/test_loop_bind_device.c#L45
```
tests/5.0/loop/test_loop_bind_device.c: In function ‘int test_loop_bind_teams()’:
tests/5.0/loop/test_loop_bind_device.c:45:27: error: OpenMP runtime API call ‘int omp_get_thread_num()’ strictly nested in a ‘teams’ region
   45 |     if (omp_get_thread_num() == 0 && omp_get_team_num() == 0) {
      |         ~~~~~~~~~~~~~~~~~~^~
tests/5.0/loop/test_loop_bind_device.c: In function ‘int test_loop_bind_thread_teams()’:
tests/5.0/loop/test_loop_bind_device.c:138:27: error: OpenMP runtime API call ‘int omp_get_thread_num()’ strictly nested in a ‘teams’ region
  138 |     if (omp_get_thread_num() == 0 && omp_get_team_num() == 0) {
      |         ~~~~~~~~~~~~~~~~~~^~
```

* https://github.com/SOLLVE/sollve_vv/blob/b87d5ef85192c56bbcd8fdeaab87eb1bbe2c1bb1/tests/5.0/loop/test_loop_nested_device.c#L45
* https://github.com/SOLLVE/sollve_vv/blob/b87d5ef85192c56bbcd8fdeaab87eb1bbe2c1bb1/tests/5.0/loop/test_loop_nested.c#L44
* https://github.com/SOLLVE/sollve_vv/blob/b87d5ef85192c56bbcd8fdeaab87eb1bbe2c1bb1/tests/5.0/loop/test_loop_bind.c#L44 and https://github.com/SOLLVE/sollve_vv/blob/b87d5ef85192c56bbcd8fdeaab87eb1bbe2c1bb1/tests/5.0/loop/test_loop_bind.c#L137
* https://github.com/SOLLVE/sollve_vv/blob/b87d5ef85192c56bbcd8fdeaab87eb1bbe2c1bb1/tests/5.0/teams/test_teams.c#L34

**Comment by tob2** [comment]
Likewise for Fortran:

 * https://github.com/SOLLVE/sollve_vv/blob/b87d5ef85192c56bbcd8fdeaab87eb1bbe2c1bb1/tests/5.0/teams/test_teams.F90#L50

**Comment by tmh97** [comment]
PR merged, closing!
