### ISSUE TITLE
5.0/task/test_task_affinity_device.c wrongly assumes unified-shared memory

### ISSUE THREAD

**Issue by tob2** [SOLLVE/sollve_vv#421]
Using `is_device_ptr` at
https://github.com/SOLLVE/sollve_vv/blob/fc187c588d379cce4c30db4a4c12bd3ba684d944/tests/5.0/task/test_task_affinity_device.c#L40
only works with unified shared memory.

One solution is the following – but surely other solutions are possible, including `requires uniform_shared_memory` ...

(Missed it before because of testing without actual offloading.)

```diff
--- a/tests/5.0/task/test_task_affinity_device.c
+++ b/tests/5.0/task/test_task_affinity_device.c
@@ -38,4 +38,6 @@ int test_task_affinity() {
 #pragma omp target enter data map(to: A[0:N])
 
+#pragma omp target data use_device_ptr(A)
+{
 #pragma omp target defaultmap(none) is_device_ptr(A) map(tofrom: B[0:N]) 
  {
@@ -56,5 +58,5 @@ int test_task_affinity() {
 #pragma omp taskwait
  }
-
+}
 
   for (int i = 0; i < N; i++) {
```

**Comment by tmh97** [comment]
@tob2 thanks again Tobias! Closing this since PR has been merged
