### ISSUE TITLE
Potential data race with 5.0/taskwait/test_taskwait_depend.c

### ISSUE THREAD

**Issue by tob2** [SOLLVE/sollve_vv#424]
The test was added in #366 ("taskwait depend") by @nolanbaker31 

https://github.com/SOLLVE/sollve_vv/blob/master/tests/5.0/taskwait/test_taskwait_depend.c

The code does the following — my impression is that the dependency does not really work as multiple threads write `i` - such that `i` can have a different value in the following. That is: The `x` vs. `y` is handled properly but `i` can do more that what is intended.

_(It does fail with GCC, which is a hint but does not proof that the testcase is wrong as it could also be a compiler bug. I still need to do some spec reading to really nail it.)_

```C
    #pragma omp parallel for
        for (int i=1; i<N; i++){
          #pragma omp task depend(inout: x) shared(x) // 1st Task
          x=i;
          #pragma omp task depend(inout: y) shared(y) // 2nd Task
          y=i;
          #pragma omp taskwait depend(in: x) //Requires the completion of the 1st task
          OMPVV_TEST_AND_SET(errors, x!= i);
          #pragma omp taskwait depend(in: x,y) //Requires the completion of both tasks
          OMPVV_TEST_AND_SET(errors, y!=i && x!=i);
        }
```

Additionally, I think the `&&` should be `||` in the second `OMPVV_TEST_AND_SET`.

**Comment by spophale** [comment]
@tob2 , yes I agree that the last condition should be an or (not an and). Also, IMO the x and y need to be private to the thread. Declaring them inside the loop passed the test with GCC 11.2.0.
But then there is a race on "errors" -- we can have atomic updates or local error variables to.
