### ISSUE TITLE
OpenMP V&V benchmark error in tests/5.0/target/test_target_mapping_before_delete.F90

### ISSUE THREAD

**Issue by seyonglee** [SOLLVE/sollve_vv#442]
**Describe the bug**
The OpenMP V&V benchmark, "tests/5.0/target/test_target_mapping_before_delete.F90" incorrectly use DELETE map-type in the map clause of a target construct. 
The OpenMP Specification V5.0 section 2.12.5 (target Construct) page 174, line 27 says "
A map-type in a map clause must be to, from, tofrom or alloc."

**Test that it applies to**
tests/5.0/target/test_target_mapping_before_delete.F90

**To Reproduce**
1. Compile the above benchmark using an OpenMP compiler (e.g., XLF 16.01)
2. Example compile command on Summit: 
$ make CC=none CXX=none FC=xlf_r ADD_BATCH_SCHED=1 SYSTEM=summit LOG=1 LOG_ALL=1 compile OMP_VERSION=5.0 SOURCES=tests/5.0/target/test_target_mapping_before_delete.F90 
4. Example error message from XLF 16.01:
"/gpfs/alpine/csc383/scratch/f6l/sollve/tests/5.0/target/test_target_mapping_before_delete.F90", line 45.53: 1514-857 (S) The map-type DELETE is not allowed in the TARGET construct.

**Expected behavior**
Remove this benchmark since it does wrong tests (trying to test the behavior of the delete map-type in the target construct where the delete map-type is not allowed). 

**Compiler**
Tested with GCC V11.1 and XLF V16.01

**Accelerator hardware**
OLCF Summit

**Comment by tmh97** [comment]
@seyonglee thanks for catching this!
