### ISSUE TITLE
Bug in test_target_enter_data_allocate_array_to.F90 

### ISSUE THREAD

**Issue by spophale** [SOLLVE/sollve_vv#48]
**Describe the bug**
Appears to contain just a simple copy/paste mistake in the error-checking logic.  The code is comparing the wrong variable, and the following changes fixes the issue:
    
    diff --git a/tests/4.5/target_enter_data/test_target_enter_data_allocate_array_to.F90 b/tests/4.5/target_enter_data/test_target_enter_data_allocate_array_to.F90
    index 88caf568..5ed6ba54 100644
    --- a/tests/4.5/target_enter_data/test_target_enter_data_allocate_array_to.F90
    +++ b/tests/4.5/target_enter_data/test_target_enter_data_allocate_array_to.F90
    @@ -141,7 +141,7 @@
     
                 ! Make sure it is not copied back
                 IF (.NOT. isSharedEnv) THEN
    -              OMPVV_TEST_AND_SET_VERBOSE(errors, ANY(my2DPtr /= 10))
    +              OMPVV_TEST_AND_SET_VERBOSE(errors, ANY(my3DPtr /= 10))
                 END IF
                 OMPVV_TEST_AND_SET_VERBOSE(errors, SUM(my3DArr) /= (N**6+N**3)/2)

**Compiler**
Provided by Cray.

**Accelerator hardware**

**Comment by josemonsalve2** [comment]
This issue was solved by PR #49
