### ISSUE TITLE
Contributing Openmp Testcases in Fortran to SOLLVE

### ISSUE THREAD

**Issue by seshakalyur** [SOLLVE/sollve_vv#510]
Hello,

I would like to contribute Fortran testcases for validating various constructs in openmp 4.5 standards.
I had the following question:
Do you ONLY accept testcases with TARGET constructs that perform CPU/GPU offloading?
or
Do you accept testcases for other openmp constructs which do not necessarily perform offloading?

Thanks and Regards,
Sesha

**Comment by spophale** [comment]
It's not just target. All *new* features introduced in 4.5 that are not covered are welcome.

**Comment by seshakalyur** [comment]
[AMD Official Use Only]

Hello Swaroop,

I was planning to submit testcases directive-by-directive basis.
So one request can contain testcases pertaining to directive
And each testcase for a unique clause for the directive.
Can you pls guide on the process to be followed.

Thanks and Regards,
Sesha

**Comment by sunitachandra** [comment]
Thank you for your interest!! Could you please email me so we can strategize this? I will connect you with the team. https://www.eecis.udel.edu/~schandra/

**Comment by seshakalyur** [comment]
@sunitachandra, @spophale, @tmh97,
I have Fortran testcases that validate every directive and all its 
Associated clauses. I can start with
The Parallel directive follow it up with the Do directive
and others. For example for the Parallel directive
I have the following testcases written which covers the
Parallel directive and its clauses as mentioned in the
Openmp 4.5 standard:

parallel_01.f08:! Validate: !$OMP PARALLEL
parallel_02.f08:! Validate: !$OMP PARALLEL IF
parallel_03.f08:! Validate: !$OMP PARALLEL NUM_THREADS
parallel_04.f08:! Validate: !$OMP PARALLEL DEFAULT
parallel_05.f08:! Validate: !$OMP PARALLEL PRIVATE
parallel_06.f08:! Validate: !$OMP PARALLEL FIRSTPRIVATE
parallel_07.f08:! Validate: !$OMP PARALLEL SHARED
parallel_08.f08:! Validate: !$OMP PARALLEL COPYIN
parallel_09.f08:! Validate: !$OMP PARALLEL REDUCTION
parallel_10.f08:! Validate: !$OMP PARALLEL PROC_BIND

Pls let me know if this is of interest to the community
and how I can get started and go about contributing 
them to SOLLVE.

Thanks

**Comment by sunitachandra** [comment]
Thanks!! As we mentioned earlier, please email us so we can strategize and plan better and also learn about your near future plans/interests on this project for continuity.

**Comment by seshakalyur** [comment]
[AMD Official Use Only]

Hello,

As I mentioned in my previous email, we would like to contribute the Openmp 4.5
testcases we have developed. These testcases are structured one for each
directive and clause combination and addresses the whole gamut of 4.5 standards.
Pls let me know of the next steps so that we can make it happen. As I said earlier
We can start with the Parallel construct first and follow up with other directives
In the order given in the 4.5 standards document.

Thanks,

**Comment by tmh97** [comment]
Hey @seshakalyur, are you still interested in contributing tests to the test suite? 

If yes, let us know :) We'll wait to hear back, if not we'll close this issue up.

Thanks!

**Comment by jrreap** [comment]
No response since April, closing this issue up until we hear otherwise.
