### ISSUE TITLE
Codes use fprintf on GPUs

### ISSUE THREAD

**Issue by spophale** [SOLLVE/sollve_vv#565]
**Is your feature request related to a problem? Please describe.**
These tests have a call to “fprintf” (printing to stderr) on the GPU (only when building with VERBOSE_MODE), but CCE only supports regular printf from the GPU:
 
https://github.com/SOLLVE/sollve_vv/blob/master/tests/5.0/target_requires/test_target_requires_atomic_default_mem_order_acq_rel.c#L41
https://github.com/SOLLVE/sollve_vv/blob/master/tests/5.0/target_requires/test_target_requires_atomic_default_mem_order_relaxed.c#L44
https://github.com/SOLLVE/sollve_vv/blob/master/tests/5.0/target_requires/test_target_requires_atomic_default_mem_order_seq_cst.c#L42

**Describe the solution you'd like**
Use printf instead.

Reported by Jeff Sandoval @ HPE

**Comment by nolanbaker31** [comment]
Fixed in pr #594, closing
