### ISSUE TITLE
Race condition in test_masked_filter.c

### ISSUE THREAD

**Issue by jakubjelinek** [SOLLVE/sollve_vv#571]
https://github.com/SOLLVE/sollve_vv/blob/8fcf5c2f92b01f3866602b5381395951ac58ad5f/tests/5.1/masked/test_masked_filter.c#L25

This is a data race, both ct and total vars are shared, while ct is only accessed in the parallel inside of masked region and so by one thread, total is decremented inside of the masked region (i.e. by one thread) but tested by all threads without any kind of synchronization in between.
Dunno what was the intent, fix could be making firstprivate(total) and moving the decrement outside of the masked region, or keeping it shared and add 2 barriers, one before and one after the masked region (then all threads will work in sync, in between 2 barriers read the shared vars and in between the other pair of barriers decrement it in masked region.  Or read and decrement total atomically.

**Comment by tob2** [comment]
Crossref: Testcase was added with Pull Request #561 by @nolanbaker31

**Comment by nolanbaker31** [comment]
PR #572 solved this. Closed.
