### ISSUE TITLE
test_target_data_use_device_ptr.c – uses undefined variable in clausesince pull req. #28

### ISSUE THREAD

**Issue by tob2** [SOLLVE/sollve_vv#61]
`test_target_data_use_device_ptr.c` was largely cleaned up in pull request #28 by @spophale. 

Unfortunately, while the declaration of `isHost` was removed, it is still used in an OpenMP clause. (See also comment in #28.) Namely, the commit ff84b5f56eafe20cb565166708c7476f7234ac77 has for `isHost:`:

```
--- a/tests/4.5/target_data/test_target_data_use_device_ptr.c
+++ b/tests/4.5/target_data/test_target_data_use_device_ptr.c
…
-  int errors = 0, len = 10000, isHost = 0;
+  int errors = 0, map_dummy;
…
+#pragma omp target is_device_ptr(array_device) map(tofrom: array_host[0:N]) map(tofrom: isHost)
```

**Comment by josemonsalve2** [comment]
Working on it.

**Comment by spophale** [comment]
Thanks!
