### ISSUE TITLE
unreliable expectation in test_target_uses_allocators_pteam

### ISSUE THREAD

**Issue by marvol77** [SOLLVE/sollve_vv#638]
The recent commit 2c8ca2d6cb28f89a3f3916b10bf416c23ca151c8 on the master branch introduced the usage of `omp_get_thread_num()` inside `#pragma omp target`. Although the clause `num_threads(8)` was specified, it is not guaranteed that eight threads are indeed available and provided from my point of view.

In section "2.6.1 Determining the Number of Threads for a parallel Region" of the OpenMP Application Programming Interface (V. 5.0) the algorithm states:
```
...
else if (dyn-var = true) and (ThreadsRequested > ThreadsAvailable)
then 1 ≤ number of threads ≤ ThreadsAvailable;
...
else if (dyn-var = false) and (ThreadsRequested > ThreadsAvailable)
then behavior is implementation defined;
```
That means, even if we try to avoid a dynamic adjustment of the number of threads (e.g. with `omp_set_dynamic`), the specified number of threads are not reliably provided.

Subsequently, `x = omp_get_thread_num();` delivers not necessarily a value between 0 and 7 but any number between 0 and the number of available threads in general. In the case that the number of available threads is less then the number of requested threads (i.e. 8), the test fails due to `result[i] != device_result[i]`.

**Comment by tob2** [comment]
Side remark: TR11 (6.0 preview) adds **strict** as _prescriptiveness_ modifier to **num_threads** (and grainsize and num_tasks). If the quoted algorithm (in TR11: Algorithm 10.1) yields fewer threads “runtime error termination is performed.”

However, the testcase is for OpenMP 5.0  (_N_ = 8) ... 
https://github.com/SOLLVE/sollve_vv/blob/a35ad17c23240aa08e95c70a1e167b006c416e2d/tests/5.0/target/test_target_uses_allocators_pteam.c#L29-L31

To increase the chance that the number of threads matches the expected number of threads, how about setting "_dyn-var_ = _false_"?

```diff
--- a/tests/5.0/target/test_target_uses_allocators_pteam.c
+++ b/tests/5.0/target/test_target_uses_allocators_pteam.c
@@ -28,2 +28,13 @@ int test_uses_allocators_pteam() {
 
+  // While the requested number of threads is 8, the resulting number of theads
+  // may be less if ThreadsAvailable < 8.
+  // As the following applies, set dyn-var to false to increase the chance that
+  // it is 8; quote from the algorith "Determine Number of Threads":
+  //   else if (dyn-var = true) and (ThreadsRequested <= ThreadsAvailable)
+  //     then 1 <= number of threads <= ThreadsRequested;
+  //   else if (dyn-var = false) and (ThreadsRequested <= ThreadsAvailable)
+  //     then number of threads = ThreadsRequested;
+
+  omp_set_dynamic(0);
+
 #pragma omp target parallel for num_threads(8) uses_allocators(omp_pteam_mem_alloc) allocate(omp_pteam_mem_alloc: x) private(x) map(from: device_result)
```

**Comment by tob2** [comment]
Related: Comment in the Pull Request #626 – this time from the LLVM side (this issue by @marvol77 is based on a GCC fail)

@ronlieb remarked there:
>  After it landed we noticed that our trunk build of LLVM/OpenMP and our local product build started failing this test.
(...) 
The quick fix is as follows: Use 64 for N, as its a multiple of wavesize for both AMD and NVPTX. Also use N in the pragma rather than 8.

CC: @spophale

**Comment by ronlieb** [comment]
not sure what SOLLVE team policy is on these sorts of problems.
perhaps author could revert the patch which broke the test, fix and repost for review ?

**Comment by spophale** [comment]
@tob2 The only problem I see with using omp_set_dynamic(0) is that the language in the specification is loose enough so that an implementation is not required to support it. I will create a patch for the test to accept number of threads such that: 1 <= x <= num_threads().

I think it will resolve the issue(s).

**Comment by tob2** [comment]
> @tob2 The only problem I see with using omp_set_dynamic(0) is that the language in the specification is loose enough so that an implementation is not required to support it. I will create a patch for the test to accept number of threads such that: 1 <= x <= num_threads().

I now also wonder whether setting _dyn-var_ on the host really affects _dyn-var_ on the device – and we want to apply it to parallel region that is inside a target region – and we use a combined directive for that.

Maybe setting _dyn-var_ is just a nice idea in term of the quoted algorithm and does not make sense _for the testcase_ in practice, especially not for **target parallel**?

**Comment by spophale** [comment]
Fair point. There is no clear direction in the spec.
