### ISSUE TITLE
Test 5.0/target_update/test_target_update_mapper_from_discontiguous.c declare mapper needs to map contiguous array section

### ISSUE THREAD

**Issue by spophale** [SOLLVE/sollve_vv#666]
**Describe the bug**
Reported by: Whitney, Brian <[brian.whitney@intel.com](mailto:brian.whitney@intel.com)>

`#pragma omp declare mapper(newvec_t v) map(v, v.data[0:v.len:2])`

Because it is in a map, it has to be a contiguous array section.

The 5.0 spec states that : If a mapper is specified for the type being mapped, or explicitly specified with the mapper map-type-modifier, then all map clauses that appear on the declare mapper directive are treated as though they appeared on the construct with the map clause.

Since map does not allow discontiguous maps, it should be:
`#pragma omp declare mapper(newvec_t v) map(v, v.data[0:v.len])`

**Test that it applies to**

5.0/target_update/test_target_update_mapper_from_discontiguous.c

**Compiler**
Intel (applicable to all)

**Comment by seyonglee** [comment]
> The 5.0 spec states that : If a mapper is specified for the type being mapped, or explicitly specified with the mapper map-type-modifier, then all map clauses that appear on the declare mapper directive are treated as though they appeared on the construct with the map clause.

The above restrictions exist in the `map` Clause section, but the user-defined mapper created using `declare mapper` directive can also be used in `target update` directive, where the above restriction does not exist and allows stride expression in the array section. 
Then, it seems to be unclear whether the above restrictions in the `map` clause section are implicitly applied to the mapper used in the `target update` directive or not.
