### ISSUE TITLE
 Distilled from SLATE 

### ISSUE THREAD

**Issue by josemonsalve2** [SOLLVE/sollve_vv#7]
Original files
[test_10.txt](https://github.com/SOLLVE/sollve_vv/files/3730440/test_10.txt)
[build-test.txt](https://github.com/SOLLVE/sollve_vv/files/3730441/build-test.txt)
[code.zip](https://github.com/SOLLVE/sollve_vv/files/3730445/code.zip)

**Comment by jhdavis8** [comment]
We decided to close this test suggestion since it relies on vendor-specific function provided by CUDA. We want to keep the suite cross-platform, so this test falls out of our scope.
