### ISSUE TITLE
Changing behavior of OMPVV_REPORT  and OMPVV_REPORT_AND_RETURN

### ISSUE THREAD

**Issue by spophale** [SOLLVE/sollve_vv#79]
**Is your feature request related to a problem? Please describe.**
Both check for OpenMP offloading support. Some tests don't do offloading and still get reported as executed on device.

**Describe the solution you'd like**
OMPVV_TEST_OFFLOADING should test offloading support and set global state. If a test does not offload then OMPVV_TEST_OFFLOADING should not be used.

Reporting macros should only look at the flag to decide where the test was executed.

**Comment by jhdavis8** [comment]
Is this issue ready to close? Fixed the behavior with PR #91
