### ISSUE TITLE
 [EXTERNAL] OpenMP Target Array reductions 

### ISSUE THREAD

**Issue by josemonsalve2** [SOLLVE/sollve_vv#8]
Dear OLCF consultants,

We are working on developing our post processing codes to make use of
GPUs using OpenMP 4.5. We have run into some difficulties when trying to
perform array reductions on the device.

We have tested two methods to perform array reductions :

    A simple reduction where the argument list to the REDUCTION clause
    contains an array, rrs of shape norder x nxh.
    !$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO REDUCTION(+:rrs)

This method results in the following run time error :

1587-175 The underlying GPU runtime reported the following error "an
illegal memory access was encountered".
1587-163 Error encountered while attempting to execute on the target
device 0. The program will stop.

    Based on Oscar's suggestion, user-defined reductions were attempted
    to implement the array reduction.

This method results in a failure at compile time :

"array_reduce_v2.F90", 1516-064 (S) Operands to the + operator must be
compatible with the intrinsic uses of the operator, or with a specific
interface within an accessible defined operator generic interface.
I remember in the past that array reductions was not supported but I
thought this is supported in the recent compiler versions.

We have consulted with Oscar from ORNL and Kevin Li from IBM regarding
this issue. Kevin suggested that 2 PMRs be opened, one for each test code.

I have generated reproducer codes with some notes in the README.txt file
on how the programs were compiled and run. These can be found in the
following tarball :

[2019-08-11-OMP-TARGET-ARRAY-REDUCTIONS.tar.gz](https://github.com/SOLLVE/sollve_vv/files/3730465/2019-08-11-OMP-TARGET-ARRAY-REDUCTIONS.tar.gz)

**Comment by jhdavis8** [comment]
See PR #68
