### ISSUE TITLE
test_taskloop_num_tasks.c failing to compile

### ISSUE THREAD

**Issue by brianwhitney59** [SOLLVE/sollve_vv#805]
test_taskloop_num_tasks.c is failing to compile.  There seems to be an unneeded ";" that is causing the if structure to fail

 64    //To check if the num_threads actually executing the parallel region > 1
 65    if(num_threads == 1)
 66      OMPVV_WARNING("Only a single thread executed the parallel region");
 67    else
 68      //if all the tasks in a group are run by a same thread, get TRUE else F    ALSE
 69      OMPVV_TEST_AND_SET_VERBOSE(errors, (isGroupIdsSame(thread_ids) != 1)); 

On line 66, the macro expands and causes multiple lines, so the else statement is left orphaned.  Removing the ";" or adding {} around the macro allow it to build.

This was found with the intel 2024.1 compiler.
icx -std=c99 -fiopenmp -fopenmp-targets=spir64 -I./ompvv -DVERBOSE_MODE=1 test_taskloop_num_tasks.c
test_taskloop_num_tasks.c:67:4: error: expected expression
   67 |    else 
      |    ^
1 error generated.

**Comment by fel-cab** [comment]
The issue was solved with PR #803
