### ISSUE TITLE
Error in testcase : tests/4.5/target_enter_data/test_target_enter_data_if.F90

### ISSUE THREAD

**Issue by shivaramaarao** [SOLLVE/sollve_vv#96]
There is a logical error in the following testcase that will result in undetermined runtime behavior.

  tests/4.5/target_enter_data/test_target_enter_data_if.F90
  @line no: 69 we have enter data which is guarded under (s > THRESHOLD)

 69              !$omp target enter data if(s > THRESHOLD) &
 70              !$omp map(to: a(1:s), b(1:s))

 @ line no: 102  we have exit data statement without guard
 102           !$omp target exit data map(delete: a(1:s), b(1:s))

if s <= THRESHOLD, there will be issues with above code.

FIX:
  
line no: 102 need to be changed as follows
102              !$omp target exit data if(s> THRESHOLD) &
103              !$omp map(delete: a(1:s), b(1:s))

**Comment by spophale** [comment]
I see the intent of your suggestion @shivaramaarao but OpenMP Sepcification 4.5 Pg 217 23-26 state that : 

> If the map clause appears on a target, target data, or target exit data construct then on exit from the region the following sequence of steps occurs:
> 1. If a corresponding list item of the original list item is not present in the device data environment, then the list item is ignored.

Are you running into implementations where this is not adhered to ? Please give details.

**Comment by shivaramaarao** [comment]
Thanks for clarification. I will close this issue at this point and get back if any clarification is required.
